version: '3.9'

name: dev_teissier_tp_frontend

services:
  next-app:
    platform: linux/x86_64
    container_name: dev.nextjs.teissier_tp
    image: dev.nextjs.teissier_tp
    ports:
      - '3000:3000'
    build:
      context: ../
      dockerfile: docker/dev.Dockerfile
    volumes:
      - ../src:/app/src
      - ../public:/app/public
