version: '3.9'

name: prod_teissier_tp_frontend

services:
  frontend-standalone:
    platform: linux/x86_64
    container_name: prod.nextjs.starter-next
    image: prod.nextjs.starter-next-js
    ports:
      - 3000:3000
    build:
      context: ../
      dockerfile: docker/prod.Dockerfile
